// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// DeleteZonesUUIDRecordsRecordNameReader is a Reader for the DeleteZonesUUIDRecordsRecordName structure.
type DeleteZonesUUIDRecordsRecordNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteZonesUUIDRecordsRecordNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteZonesUUIDRecordsRecordNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteZonesUUIDRecordsRecordNameOK creates a DeleteZonesUUIDRecordsRecordNameOK with default headers values
func NewDeleteZonesUUIDRecordsRecordNameOK() *DeleteZonesUUIDRecordsRecordNameOK {
	return &DeleteZonesUUIDRecordsRecordNameOK{}
}

/*DeleteZonesUUIDRecordsRecordNameOK handles this case with default header values.

OK
*/
type DeleteZonesUUIDRecordsRecordNameOK struct {
	Payload *models.ReturnMessage
}

func (o *DeleteZonesUUIDRecordsRecordNameOK) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}/records/{record_name}][%d] deleteZonesUuidRecordsRecordNameOK  %+v", 200, o.Payload)
}

func (o *DeleteZonesUUIDRecordsRecordNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
