// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// DeleteZonesUUIDRecordsReader is a Reader for the DeleteZonesUUIDRecords structure.
type DeleteZonesUUIDRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteZonesUUIDRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteZonesUUIDRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteZonesUUIDRecordsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteZonesUUIDRecordsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteZonesUUIDRecordsOK creates a DeleteZonesUUIDRecordsOK with default headers values
func NewDeleteZonesUUIDRecordsOK() *DeleteZonesUUIDRecordsOK {
	return &DeleteZonesUUIDRecordsOK{}
}

/*DeleteZonesUUIDRecordsOK handles this case with default header values.

OK
*/
type DeleteZonesUUIDRecordsOK struct {
	Payload *models.Return200
}

func (o *DeleteZonesUUIDRecordsOK) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}/records][%d] deleteZonesUuidRecordsOK  %+v", 200, o.Payload)
}

func (o *DeleteZonesUUIDRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteZonesUUIDRecordsBadRequest creates a DeleteZonesUUIDRecordsBadRequest with default headers values
func NewDeleteZonesUUIDRecordsBadRequest() *DeleteZonesUUIDRecordsBadRequest {
	return &DeleteZonesUUIDRecordsBadRequest{}
}

/*DeleteZonesUUIDRecordsBadRequest handles this case with default header values.

Not OK
*/
type DeleteZonesUUIDRecordsBadRequest struct {
	Payload *models.Return400
}

func (o *DeleteZonesUUIDRecordsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}/records][%d] deleteZonesUuidRecordsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteZonesUUIDRecordsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteZonesUUIDRecordsDefault creates a DeleteZonesUUIDRecordsDefault with default headers values
func NewDeleteZonesUUIDRecordsDefault(code int) *DeleteZonesUUIDRecordsDefault {
	return &DeleteZonesUUIDRecordsDefault{
		_statusCode: code,
	}
}

/*DeleteZonesUUIDRecordsDefault handles this case with default header values.

Unexpected error
*/
type DeleteZonesUUIDRecordsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the delete zones UUID records default response
func (o *DeleteZonesUUIDRecordsDefault) Code() int {
	return o._statusCode
}

func (o *DeleteZonesUUIDRecordsDefault) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}/records][%d] DeleteZonesUUIDRecords default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteZonesUUIDRecordsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
