// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// DeleteZonesUUIDRecordsRecordNameRecordTypeReader is a Reader for the DeleteZonesUUIDRecordsRecordNameRecordType structure.
type DeleteZonesUUIDRecordsRecordNameRecordTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteZonesUUIDRecordsRecordNameRecordTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteZonesUUIDRecordsRecordNameRecordTypeOK creates a DeleteZonesUUIDRecordsRecordNameRecordTypeOK with default headers values
func NewDeleteZonesUUIDRecordsRecordNameRecordTypeOK() *DeleteZonesUUIDRecordsRecordNameRecordTypeOK {
	return &DeleteZonesUUIDRecordsRecordNameRecordTypeOK{}
}

/*DeleteZonesUUIDRecordsRecordNameRecordTypeOK handles this case with default header values.

OK
*/
type DeleteZonesUUIDRecordsRecordNameRecordTypeOK struct {
	Payload *models.ReturnMessage
}

func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeOK) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}/records/{record_name}/{record_type}][%d] deleteZonesUuidRecordsRecordNameRecordTypeOK  %+v", 200, o.Payload)
}

func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
