// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteZonesUUIDRecordsNameTypeParams creates a new DeleteZonesUUIDRecordsNameTypeParams object
// with the default values initialized.
func NewDeleteZonesUUIDRecordsNameTypeParams() *DeleteZonesUUIDRecordsNameTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsNameTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteZonesUUIDRecordsNameTypeParamsWithTimeout creates a new DeleteZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteZonesUUIDRecordsNameTypeParamsWithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsNameTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsNameTypeParams{

		timeout: timeout,
	}
}

// NewDeleteZonesUUIDRecordsNameTypeParamsWithContext creates a new DeleteZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteZonesUUIDRecordsNameTypeParamsWithContext(ctx context.Context) *DeleteZonesUUIDRecordsNameTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsNameTypeParams{

		Context: ctx,
	}
}

// NewDeleteZonesUUIDRecordsNameTypeParamsWithHTTPClient creates a new DeleteZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteZonesUUIDRecordsNameTypeParamsWithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsNameTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsNameTypeParams{
		HTTPClient: client,
	}
}

/*DeleteZonesUUIDRecordsNameTypeParams contains all the parameters to send to the API endpoint
for the delete zones UUID records name type operation typically these are written to a http.Request
*/
type DeleteZonesUUIDRecordsNameTypeParams struct {

	/*Name
	  Record name

	*/
	Name string
	/*Type
	  Record type

	*/
	Type string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithContext(ctx context.Context) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithName(name string) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetName(name string) {
	o.Name = name
}

// WithType adds the typeVar to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithType(typeVar string) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WithUUID adds the uuid to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) WithUUID(uuid string) *DeleteZonesUUIDRecordsNameTypeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete zones UUID records name type params
func (o *DeleteZonesUUIDRecordsNameTypeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteZonesUUIDRecordsNameTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
