// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteZonesUUIDRecordsNameParams creates a new DeleteZonesUUIDRecordsNameParams object
// with the default values initialized.
func NewDeleteZonesUUIDRecordsNameParams() *DeleteZonesUUIDRecordsNameParams {
	var ()
	return &DeleteZonesUUIDRecordsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteZonesUUIDRecordsNameParamsWithTimeout creates a new DeleteZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteZonesUUIDRecordsNameParamsWithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsNameParams {
	var ()
	return &DeleteZonesUUIDRecordsNameParams{

		timeout: timeout,
	}
}

// NewDeleteZonesUUIDRecordsNameParamsWithContext creates a new DeleteZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteZonesUUIDRecordsNameParamsWithContext(ctx context.Context) *DeleteZonesUUIDRecordsNameParams {
	var ()
	return &DeleteZonesUUIDRecordsNameParams{

		Context: ctx,
	}
}

// NewDeleteZonesUUIDRecordsNameParamsWithHTTPClient creates a new DeleteZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteZonesUUIDRecordsNameParamsWithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsNameParams {
	var ()
	return &DeleteZonesUUIDRecordsNameParams{
		HTTPClient: client,
	}
}

/*DeleteZonesUUIDRecordsNameParams contains all the parameters to send to the API endpoint
for the delete zones UUID records name operation typically these are written to a http.Request
*/
type DeleteZonesUUIDRecordsNameParams struct {

	/*Name
	  Record name

	*/
	Name string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) WithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) WithContext(ctx context.Context) *DeleteZonesUUIDRecordsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) WithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) WithName(name string) *DeleteZonesUUIDRecordsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) SetName(name string) {
	o.Name = name
}

// WithUUID adds the uuid to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) WithUUID(uuid string) *DeleteZonesUUIDRecordsNameParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete zones UUID records name params
func (o *DeleteZonesUUIDRecordsNameParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteZonesUUIDRecordsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
