// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteZonesUUIDRecordsRecordNameRecordTypeParams creates a new DeleteZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized.
func NewDeleteZonesUUIDRecordsRecordNameRecordTypeParams() *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsRecordNameRecordTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithTimeout creates a new DeleteZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsRecordNameRecordTypeParams{

		timeout: timeout,
	}
}

// NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithContext creates a new DeleteZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithContext(ctx context.Context) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsRecordNameRecordTypeParams{

		Context: ctx,
	}
}

// NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithHTTPClient creates a new DeleteZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteZonesUUIDRecordsRecordNameRecordTypeParamsWithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &DeleteZonesUUIDRecordsRecordNameRecordTypeParams{
		HTTPClient: client,
	}
}

/*DeleteZonesUUIDRecordsRecordNameRecordTypeParams contains all the parameters to send to the API endpoint
for the delete zones UUID records record name record type operation typically these are written to a http.Request
*/
type DeleteZonesUUIDRecordsRecordNameRecordTypeParams struct {

	/*RecordName
	  Record name

	*/
	RecordName string
	/*RecordType
	  Record type

	*/
	RecordType string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithTimeout(timeout time.Duration) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithContext(ctx context.Context) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithHTTPClient(client *http.Client) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordName adds the recordName to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithRecordName(recordName string) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetRecordName(recordName)
	return o
}

// SetRecordName adds the recordName to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetRecordName(recordName string) {
	o.RecordName = recordName
}

// WithRecordType adds the recordType to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithRecordType(recordType string) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetRecordType(recordType)
	return o
}

// SetRecordType adds the recordType to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetRecordType(recordType string) {
	o.RecordType = recordType
}

// WithUUID adds the uuid to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WithUUID(uuid string) *DeleteZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete zones UUID records record name record type params
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteZonesUUIDRecordsRecordNameRecordTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param record_name
	if err := r.SetPathParam("record_name", o.RecordName); err != nil {
		return err
	}

	// path param record_type
	if err := r.SetPathParam("record_type", o.RecordType); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
