// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetZonesUUIDRecordsRecordNameReader is a Reader for the GetZonesUUIDRecordsRecordName structure.
type GetZonesUUIDRecordsRecordNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDRecordsRecordNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDRecordsRecordNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetZonesUUIDRecordsRecordNameOK creates a GetZonesUUIDRecordsRecordNameOK with default headers values
func NewGetZonesUUIDRecordsRecordNameOK() *GetZonesUUIDRecordsRecordNameOK {
	return &GetZonesUUIDRecordsRecordNameOK{}
}

/*GetZonesUUIDRecordsRecordNameOK handles this case with default header values.

OK
*/
type GetZonesUUIDRecordsRecordNameOK struct {
	Payload []*models.Record
}

func (o *GetZonesUUIDRecordsRecordNameOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/records/{record_name}][%d] getZonesUuidRecordsRecordNameOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDRecordsRecordNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
