// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/tokart/gandi-livedns-go/models"
)

// GetZonesUUIDRecordsReader is a Reader for the GetZonesUUIDRecords structure.
type GetZonesUUIDRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetZonesUUIDRecordsOK creates a GetZonesUUIDRecordsOK with default headers values
func NewGetZonesUUIDRecordsOK() *GetZonesUUIDRecordsOK {
	return &GetZonesUUIDRecordsOK{}
}

/*GetZonesUUIDRecordsOK handles this case with default header values.

OK
*/
type GetZonesUUIDRecordsOK struct {
	Payload []*models.Record
}

func (o *GetZonesUUIDRecordsOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/records][%d] getZonesUuidRecordsOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
