// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDRecordsRecordNameParams creates a new GetZonesUUIDRecordsRecordNameParams object
// with the default values initialized.
func NewGetZonesUUIDRecordsRecordNameParams() *GetZonesUUIDRecordsRecordNameParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDRecordsRecordNameParamsWithTimeout creates a new GetZonesUUIDRecordsRecordNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDRecordsRecordNameParamsWithTimeout(timeout time.Duration) *GetZonesUUIDRecordsRecordNameParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDRecordsRecordNameParamsWithContext creates a new GetZonesUUIDRecordsRecordNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDRecordsRecordNameParamsWithContext(ctx context.Context) *GetZonesUUIDRecordsRecordNameParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDRecordsRecordNameParamsWithHTTPClient creates a new GetZonesUUIDRecordsRecordNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDRecordsRecordNameParamsWithHTTPClient(client *http.Client) *GetZonesUUIDRecordsRecordNameParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDRecordsRecordNameParams contains all the parameters to send to the API endpoint
for the get zones UUID records record name operation typically these are written to a http.Request
*/
type GetZonesUUIDRecordsRecordNameParams struct {

	/*RecordName
	  Record name

	*/
	RecordName string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) WithTimeout(timeout time.Duration) *GetZonesUUIDRecordsRecordNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) WithContext(ctx context.Context) *GetZonesUUIDRecordsRecordNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) WithHTTPClient(client *http.Client) *GetZonesUUIDRecordsRecordNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordName adds the recordName to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) WithRecordName(recordName string) *GetZonesUUIDRecordsRecordNameParams {
	o.SetRecordName(recordName)
	return o
}

// SetRecordName adds the recordName to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) SetRecordName(recordName string) {
	o.RecordName = recordName
}

// WithUUID adds the uuid to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) WithUUID(uuid string) *GetZonesUUIDRecordsRecordNameParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID records record name params
func (o *GetZonesUUIDRecordsRecordNameParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDRecordsRecordNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param record_name
	if err := r.SetPathParam("record_name", o.RecordName); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
