// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetZonesUUIDRecordsNameReader is a Reader for the GetZonesUUIDRecordsName structure.
type GetZonesUUIDRecordsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDRecordsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDRecordsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetZonesUUIDRecordsNameOK creates a GetZonesUUIDRecordsNameOK with default headers values
func NewGetZonesUUIDRecordsNameOK() *GetZonesUUIDRecordsNameOK {
	return &GetZonesUUIDRecordsNameOK{}
}

/*GetZonesUUIDRecordsNameOK handles this case with default header values.

OK
*/
type GetZonesUUIDRecordsNameOK struct {
	Payload []*models.Record
}

func (o *GetZonesUUIDRecordsNameOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/records/{name}][%d] getZonesUuidRecordsNameOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDRecordsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
