// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDRecordsNameTypeParams creates a new GetZonesUUIDRecordsNameTypeParams object
// with the default values initialized.
func NewGetZonesUUIDRecordsNameTypeParams() *GetZonesUUIDRecordsNameTypeParams {
	var ()
	return &GetZonesUUIDRecordsNameTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDRecordsNameTypeParamsWithTimeout creates a new GetZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDRecordsNameTypeParamsWithTimeout(timeout time.Duration) *GetZonesUUIDRecordsNameTypeParams {
	var ()
	return &GetZonesUUIDRecordsNameTypeParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDRecordsNameTypeParamsWithContext creates a new GetZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDRecordsNameTypeParamsWithContext(ctx context.Context) *GetZonesUUIDRecordsNameTypeParams {
	var ()
	return &GetZonesUUIDRecordsNameTypeParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDRecordsNameTypeParamsWithHTTPClient creates a new GetZonesUUIDRecordsNameTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDRecordsNameTypeParamsWithHTTPClient(client *http.Client) *GetZonesUUIDRecordsNameTypeParams {
	var ()
	return &GetZonesUUIDRecordsNameTypeParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDRecordsNameTypeParams contains all the parameters to send to the API endpoint
for the get zones UUID records name type operation typically these are written to a http.Request
*/
type GetZonesUUIDRecordsNameTypeParams struct {

	/*Name
	  Record name

	*/
	Name string
	/*Type
	  Record type

	*/
	Type string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithTimeout(timeout time.Duration) *GetZonesUUIDRecordsNameTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithContext(ctx context.Context) *GetZonesUUIDRecordsNameTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithHTTPClient(client *http.Client) *GetZonesUUIDRecordsNameTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithName(name string) *GetZonesUUIDRecordsNameTypeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetName(name string) {
	o.Name = name
}

// WithType adds the typeVar to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithType(typeVar string) *GetZonesUUIDRecordsNameTypeParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WithUUID adds the uuid to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) WithUUID(uuid string) *GetZonesUUIDRecordsNameTypeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID records name type params
func (o *GetZonesUUIDRecordsNameTypeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDRecordsNameTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
