// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDRecordsRecordNameRecordTypeParams creates a new GetZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized.
func NewGetZonesUUIDRecordsRecordNameRecordTypeParams() *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameRecordTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithTimeout creates a new GetZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithTimeout(timeout time.Duration) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameRecordTypeParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithContext creates a new GetZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithContext(ctx context.Context) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameRecordTypeParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithHTTPClient creates a new GetZonesUUIDRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDRecordsRecordNameRecordTypeParamsWithHTTPClient(client *http.Client) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	var ()
	return &GetZonesUUIDRecordsRecordNameRecordTypeParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDRecordsRecordNameRecordTypeParams contains all the parameters to send to the API endpoint
for the get zones UUID records record name record type operation typically these are written to a http.Request
*/
type GetZonesUUIDRecordsRecordNameRecordTypeParams struct {

	/*RecordName
	  Record name

	*/
	RecordName string
	/*RecordType
	  Record type

	*/
	RecordType string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithTimeout(timeout time.Duration) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithContext(ctx context.Context) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithHTTPClient(client *http.Client) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecordName adds the recordName to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithRecordName(recordName string) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetRecordName(recordName)
	return o
}

// SetRecordName adds the recordName to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetRecordName(recordName string) {
	o.RecordName = recordName
}

// WithRecordType adds the recordType to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithRecordType(recordType string) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetRecordType(recordType)
	return o
}

// SetRecordType adds the recordType to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetRecordType(recordType string) {
	o.RecordType = recordType
}

// WithUUID adds the uuid to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WithUUID(uuid string) *GetZonesUUIDRecordsRecordNameRecordTypeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID records record name record type params
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDRecordsRecordNameRecordTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param record_name
	if err := r.SetPathParam("record_name", o.RecordName); err != nil {
		return err
	}

	// path param record_type
	if err := r.SetPathParam("record_type", o.RecordType); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
