// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDRecordsNameParams creates a new GetZonesUUIDRecordsNameParams object
// with the default values initialized.
func NewGetZonesUUIDRecordsNameParams() *GetZonesUUIDRecordsNameParams {
	var ()
	return &GetZonesUUIDRecordsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDRecordsNameParamsWithTimeout creates a new GetZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDRecordsNameParamsWithTimeout(timeout time.Duration) *GetZonesUUIDRecordsNameParams {
	var ()
	return &GetZonesUUIDRecordsNameParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDRecordsNameParamsWithContext creates a new GetZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDRecordsNameParamsWithContext(ctx context.Context) *GetZonesUUIDRecordsNameParams {
	var ()
	return &GetZonesUUIDRecordsNameParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDRecordsNameParamsWithHTTPClient creates a new GetZonesUUIDRecordsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDRecordsNameParamsWithHTTPClient(client *http.Client) *GetZonesUUIDRecordsNameParams {
	var ()
	return &GetZonesUUIDRecordsNameParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDRecordsNameParams contains all the parameters to send to the API endpoint
for the get zones UUID records name operation typically these are written to a http.Request
*/
type GetZonesUUIDRecordsNameParams struct {

	/*Name
	  Record name

	*/
	Name string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) WithTimeout(timeout time.Duration) *GetZonesUUIDRecordsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) WithContext(ctx context.Context) *GetZonesUUIDRecordsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) WithHTTPClient(client *http.Client) *GetZonesUUIDRecordsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) WithName(name string) *GetZonesUUIDRecordsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) SetName(name string) {
	o.Name = name
}

// WithUUID adds the uuid to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) WithUUID(uuid string) *GetZonesUUIDRecordsNameParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID records name params
func (o *GetZonesUUIDRecordsNameParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDRecordsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
