// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDRecordsParams creates a new GetZonesUUIDRecordsParams object
// with the default values initialized.
func NewGetZonesUUIDRecordsParams() *GetZonesUUIDRecordsParams {
	var ()
	return &GetZonesUUIDRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDRecordsParamsWithTimeout creates a new GetZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDRecordsParamsWithTimeout(timeout time.Duration) *GetZonesUUIDRecordsParams {
	var ()
	return &GetZonesUUIDRecordsParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDRecordsParamsWithContext creates a new GetZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDRecordsParamsWithContext(ctx context.Context) *GetZonesUUIDRecordsParams {
	var ()
	return &GetZonesUUIDRecordsParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDRecordsParamsWithHTTPClient creates a new GetZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDRecordsParamsWithHTTPClient(client *http.Client) *GetZonesUUIDRecordsParams {
	var ()
	return &GetZonesUUIDRecordsParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDRecordsParams contains all the parameters to send to the API endpoint
for the get zones UUID records operation typically these are written to a http.Request
*/
type GetZonesUUIDRecordsParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) WithTimeout(timeout time.Duration) *GetZonesUUIDRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) WithContext(ctx context.Context) *GetZonesUUIDRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) WithHTTPClient(client *http.Client) *GetZonesUUIDRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) WithUUID(uuid string) *GetZonesUUIDRecordsParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID records params
func (o *GetZonesUUIDRecordsParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
