// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PostZonesUUIDRecordsReader is a Reader for the PostZonesUUIDRecords structure.
type PostZonesUUIDRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostZonesUUIDRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostZonesUUIDRecordsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostZonesUUIDRecordsCreated creates a PostZonesUUIDRecordsCreated with default headers values
func NewPostZonesUUIDRecordsCreated() *PostZonesUUIDRecordsCreated {
	return &PostZonesUUIDRecordsCreated{}
}

/*PostZonesUUIDRecordsCreated handles this case with default header values.

OK
*/
type PostZonesUUIDRecordsCreated struct {
	Payload *models.ReturnMessage
}

func (o *PostZonesUUIDRecordsCreated) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/records][%d] postZonesUuidRecordsCreated  %+v", 201, o.Payload)
}

func (o *PostZonesUUIDRecordsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
