// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PostZonesUUIDRecordsReader is a Reader for the PostZonesUUIDRecords structure.
type PostZonesUUIDRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostZonesUUIDRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostZonesUUIDRecordsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostZonesUUIDRecordsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostZonesUUIDRecordsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostZonesUUIDRecordsCreated creates a PostZonesUUIDRecordsCreated with default headers values
func NewPostZonesUUIDRecordsCreated() *PostZonesUUIDRecordsCreated {
	return &PostZonesUUIDRecordsCreated{}
}

/*PostZonesUUIDRecordsCreated handles this case with default header values.

OK
*/
type PostZonesUUIDRecordsCreated struct {
	Payload *models.Return200
}

func (o *PostZonesUUIDRecordsCreated) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/records][%d] postZonesUuidRecordsCreated  %+v", 201, o.Payload)
}

func (o *PostZonesUUIDRecordsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesUUIDRecordsBadRequest creates a PostZonesUUIDRecordsBadRequest with default headers values
func NewPostZonesUUIDRecordsBadRequest() *PostZonesUUIDRecordsBadRequest {
	return &PostZonesUUIDRecordsBadRequest{}
}

/*PostZonesUUIDRecordsBadRequest handles this case with default header values.

Not OK
*/
type PostZonesUUIDRecordsBadRequest struct {
	Payload *models.Return400
}

func (o *PostZonesUUIDRecordsBadRequest) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/records][%d] postZonesUuidRecordsBadRequest  %+v", 400, o.Payload)
}

func (o *PostZonesUUIDRecordsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesUUIDRecordsDefault creates a PostZonesUUIDRecordsDefault with default headers values
func NewPostZonesUUIDRecordsDefault(code int) *PostZonesUUIDRecordsDefault {
	return &PostZonesUUIDRecordsDefault{
		_statusCode: code,
	}
}

/*PostZonesUUIDRecordsDefault handles this case with default header values.

Unexpected error
*/
type PostZonesUUIDRecordsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the post zones UUID records default response
func (o *PostZonesUUIDRecordsDefault) Code() int {
	return o._statusCode
}

func (o *PostZonesUUIDRecordsDefault) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/records][%d] PostZonesUUIDRecords default  %+v", o._statusCode, o.Payload)
}

func (o *PostZonesUUIDRecordsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
