// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
	"golang.org/x/net/context"
)

// NewPutZonesUUIDRecordsParams creates a new PutZonesUUIDRecordsParams object
// with the default values initialized.
func NewPutZonesUUIDRecordsParams() *PutZonesUUIDRecordsParams {
	var ()
	return &PutZonesUUIDRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutZonesUUIDRecordsParamsWithTimeout creates a new PutZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutZonesUUIDRecordsParamsWithTimeout(timeout time.Duration) *PutZonesUUIDRecordsParams {
	var ()
	return &PutZonesUUIDRecordsParams{

		timeout: timeout,
	}
}

// NewPutZonesUUIDRecordsParamsWithContext creates a new PutZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutZonesUUIDRecordsParamsWithContext(ctx context.Context) *PutZonesUUIDRecordsParams {
	var ()
	return &PutZonesUUIDRecordsParams{

		Context: ctx,
	}
}

// NewPutZonesUUIDRecordsParamsWithHTTPClient creates a new PutZonesUUIDRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutZonesUUIDRecordsParamsWithHTTPClient(client *http.Client) *PutZonesUUIDRecordsParams {
	var ()
	return &PutZonesUUIDRecordsParams{
		HTTPClient: client,
	}
}

/*PutZonesUUIDRecordsParams contains all the parameters to send to the API endpoint
for the put zones UUID records operation typically these are written to a http.Request
*/
type PutZonesUUIDRecordsParams struct {

	/*Record
	  Zone name

	*/
	Record []*models.Record
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) WithTimeout(timeout time.Duration) *PutZonesUUIDRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) WithContext(ctx context.Context) *PutZonesUUIDRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) WithHTTPClient(client *http.Client) *PutZonesUUIDRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecord adds the record to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) WithRecord(record []*models.Record) *PutZonesUUIDRecordsParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) SetRecord(record []*models.Record) {
	o.Record = record
}

// WithUUID adds the uuid to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) WithUUID(uuid string) *PutZonesUUIDRecordsParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put zones UUID records params
func (o *PutZonesUUIDRecordsParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutZonesUUIDRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
