// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PutZonesUUIDRecordsReader is a Reader for the PutZonesUUIDRecords structure.
type PutZonesUUIDRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutZonesUUIDRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutZonesUUIDRecordsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutZonesUUIDRecordsCreated creates a PutZonesUUIDRecordsCreated with default headers values
func NewPutZonesUUIDRecordsCreated() *PutZonesUUIDRecordsCreated {
	return &PutZonesUUIDRecordsCreated{}
}

/*PutZonesUUIDRecordsCreated handles this case with default header values.

OK
*/
type PutZonesUUIDRecordsCreated struct {
	Payload *models.ReturnMessage
}

func (o *PutZonesUUIDRecordsCreated) Error() string {
	return fmt.Sprintf("[PUT /zones/{uuid}/records][%d] putZonesUuidRecordsCreated  %+v", 201, o.Payload)
}

func (o *PutZonesUUIDRecordsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
