// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetDomainsDomainRecordsRecordNameParams creates a new GetDomainsDomainRecordsRecordNameParams object
// with the default values initialized.
func NewGetDomainsDomainRecordsRecordNameParams() *GetDomainsDomainRecordsRecordNameParams {
	var ()
	return &GetDomainsDomainRecordsRecordNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsDomainRecordsRecordNameParamsWithTimeout creates a new GetDomainsDomainRecordsRecordNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainsDomainRecordsRecordNameParamsWithTimeout(timeout time.Duration) *GetDomainsDomainRecordsRecordNameParams {
	var ()
	return &GetDomainsDomainRecordsRecordNameParams{

		timeout: timeout,
	}
}

// NewGetDomainsDomainRecordsRecordNameParamsWithContext creates a new GetDomainsDomainRecordsRecordNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainsDomainRecordsRecordNameParamsWithContext(ctx context.Context) *GetDomainsDomainRecordsRecordNameParams {
	var ()
	return &GetDomainsDomainRecordsRecordNameParams{

		Context: ctx,
	}
}

// NewGetDomainsDomainRecordsRecordNameParamsWithHTTPClient creates a new GetDomainsDomainRecordsRecordNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDomainsDomainRecordsRecordNameParamsWithHTTPClient(client *http.Client) *GetDomainsDomainRecordsRecordNameParams {
	var ()
	return &GetDomainsDomainRecordsRecordNameParams{
		HTTPClient: client,
	}
}

/*GetDomainsDomainRecordsRecordNameParams contains all the parameters to send to the API endpoint
for the get domains domain records record name operation typically these are written to a http.Request
*/
type GetDomainsDomainRecordsRecordNameParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*RecordName
	  record name to inspect

	*/
	RecordName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) WithTimeout(timeout time.Duration) *GetDomainsDomainRecordsRecordNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) WithContext(ctx context.Context) *GetDomainsDomainRecordsRecordNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) WithHTTPClient(client *http.Client) *GetDomainsDomainRecordsRecordNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) WithDomain(domain string) *GetDomainsDomainRecordsRecordNameParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithRecordName adds the recordName to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) WithRecordName(recordName string) *GetDomainsDomainRecordsRecordNameParams {
	o.SetRecordName(recordName)
	return o
}

// SetRecordName adds the recordName to the get domains domain records record name params
func (o *GetDomainsDomainRecordsRecordNameParams) SetRecordName(recordName string) {
	o.RecordName = recordName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsDomainRecordsRecordNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	// path param record_name
	if err := r.SetPathParam("record_name", o.RecordName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
