// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetDomainsDomainReader is a Reader for the GetDomainsDomain structure.
type GetDomainsDomainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsDomainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDomainsDomainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDomainsDomainBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetDomainsDomainDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDomainsDomainOK creates a GetDomainsDomainOK with default headers values
func NewGetDomainsDomainOK() *GetDomainsDomainOK {
	return &GetDomainsDomainOK{}
}

/*GetDomainsDomainOK handles this case with default header values.

OK
*/
type GetDomainsDomainOK struct {
	Payload []*GetDomainsDomainOKBodyItems0
}

func (o *GetDomainsDomainOK) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}][%d] getDomainsDomainOK  %+v", 200, o.Payload)
}

func (o *GetDomainsDomainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsDomainBadRequest creates a GetDomainsDomainBadRequest with default headers values
func NewGetDomainsDomainBadRequest() *GetDomainsDomainBadRequest {
	return &GetDomainsDomainBadRequest{}
}

/*GetDomainsDomainBadRequest handles this case with default header values.

Not OK
*/
type GetDomainsDomainBadRequest struct {
	Payload *models.Return400
}

func (o *GetDomainsDomainBadRequest) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}][%d] getDomainsDomainBadRequest  %+v", 400, o.Payload)
}

func (o *GetDomainsDomainBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsDomainDefault creates a GetDomainsDomainDefault with default headers values
func NewGetDomainsDomainDefault(code int) *GetDomainsDomainDefault {
	return &GetDomainsDomainDefault{
		_statusCode: code,
	}
}

/*GetDomainsDomainDefault handles this case with default header values.

Unexpected error
*/
type GetDomainsDomainDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the get domains domain default response
func (o *GetDomainsDomainDefault) Code() int {
	return o._statusCode
}

func (o *GetDomainsDomainDefault) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}][%d] GetDomainsDomain default  %+v", o._statusCode, o.Payload)
}

func (o *GetDomainsDomainDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetDomainsDomainOKBodyItems0 get domains domain o k body items0
swagger:model GetDomainsDomainOKBodyItems0
*/
type GetDomainsDomainOKBodyItems0 struct {

	// fqdn
	Fqdn string `json:"fqdn,omitempty"`

	// zone
	Zone string `json:"zone,omitempty"`

	// zonedata
	Zonedata string `json:"zonedata,omitempty"`
}

// Validate validates this get domains domain o k body items0
func (o *GetDomainsDomainOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDomainsDomainOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDomainsDomainOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetDomainsDomainOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
