// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetDomainsDomainParams creates a new GetDomainsDomainParams object
// with the default values initialized.
func NewGetDomainsDomainParams() *GetDomainsDomainParams {
	var ()
	return &GetDomainsDomainParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsDomainParamsWithTimeout creates a new GetDomainsDomainParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainsDomainParamsWithTimeout(timeout time.Duration) *GetDomainsDomainParams {
	var ()
	return &GetDomainsDomainParams{

		timeout: timeout,
	}
}

// NewGetDomainsDomainParamsWithContext creates a new GetDomainsDomainParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainsDomainParamsWithContext(ctx context.Context) *GetDomainsDomainParams {
	var ()
	return &GetDomainsDomainParams{

		Context: ctx,
	}
}

// NewGetDomainsDomainParamsWithHTTPClient creates a new GetDomainsDomainParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDomainsDomainParamsWithHTTPClient(client *http.Client) *GetDomainsDomainParams {
	var ()
	return &GetDomainsDomainParams{
		HTTPClient: client,
	}
}

/*GetDomainsDomainParams contains all the parameters to send to the API endpoint
for the get domains domain operation typically these are written to a http.Request
*/
type GetDomainsDomainParams struct {

	/*Domain
	  Domaine to inspect

	*/
	Domain string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domains domain params
func (o *GetDomainsDomainParams) WithTimeout(timeout time.Duration) *GetDomainsDomainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains domain params
func (o *GetDomainsDomainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains domain params
func (o *GetDomainsDomainParams) WithContext(ctx context.Context) *GetDomainsDomainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains domain params
func (o *GetDomainsDomainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains domain params
func (o *GetDomainsDomainParams) WithHTTPClient(client *http.Client) *GetDomainsDomainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains domain params
func (o *GetDomainsDomainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get domains domain params
func (o *GetDomainsDomainParams) WithDomain(domain string) *GetDomainsDomainParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get domains domain params
func (o *GetDomainsDomainParams) SetDomain(domain string) {
	o.Domain = domain
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsDomainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
