// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetDomainsDomainRecordsNameTypeReader is a Reader for the GetDomainsDomainRecordsNameType structure.
type GetDomainsDomainRecordsNameTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsDomainRecordsNameTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDomainsDomainRecordsNameTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDomainsDomainRecordsNameTypeOK creates a GetDomainsDomainRecordsNameTypeOK with default headers values
func NewGetDomainsDomainRecordsNameTypeOK() *GetDomainsDomainRecordsNameTypeOK {
	return &GetDomainsDomainRecordsNameTypeOK{}
}

/*GetDomainsDomainRecordsNameTypeOK handles this case with default header values.

OK
*/
type GetDomainsDomainRecordsNameTypeOK struct {
	Payload []*models.Record
}

func (o *GetDomainsDomainRecordsNameTypeOK) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}/records/{name}/{type}][%d] getDomainsDomainRecordsNameTypeOK  %+v", 200, o.Payload)
}

func (o *GetDomainsDomainRecordsNameTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
