// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetDomainsDomainRecordsReader is a Reader for the GetDomainsDomainRecords structure.
type GetDomainsDomainRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsDomainRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDomainsDomainRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDomainsDomainRecordsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetDomainsDomainRecordsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDomainsDomainRecordsOK creates a GetDomainsDomainRecordsOK with default headers values
func NewGetDomainsDomainRecordsOK() *GetDomainsDomainRecordsOK {
	return &GetDomainsDomainRecordsOK{}
}

/*GetDomainsDomainRecordsOK handles this case with default header values.

OK
*/
type GetDomainsDomainRecordsOK struct {
	Payload []*models.Record
}

func (o *GetDomainsDomainRecordsOK) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}/records][%d] getDomainsDomainRecordsOK  %+v", 200, o.Payload)
}

func (o *GetDomainsDomainRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsDomainRecordsBadRequest creates a GetDomainsDomainRecordsBadRequest with default headers values
func NewGetDomainsDomainRecordsBadRequest() *GetDomainsDomainRecordsBadRequest {
	return &GetDomainsDomainRecordsBadRequest{}
}

/*GetDomainsDomainRecordsBadRequest handles this case with default header values.

Not OK
*/
type GetDomainsDomainRecordsBadRequest struct {
	Payload *models.Return400
}

func (o *GetDomainsDomainRecordsBadRequest) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}/records][%d] getDomainsDomainRecordsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDomainsDomainRecordsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsDomainRecordsDefault creates a GetDomainsDomainRecordsDefault with default headers values
func NewGetDomainsDomainRecordsDefault(code int) *GetDomainsDomainRecordsDefault {
	return &GetDomainsDomainRecordsDefault{
		_statusCode: code,
	}
}

/*GetDomainsDomainRecordsDefault handles this case with default header values.

Unexpected error
*/
type GetDomainsDomainRecordsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the get domains domain records default response
func (o *GetDomainsDomainRecordsDefault) Code() int {
	return o._statusCode
}

func (o *GetDomainsDomainRecordsDefault) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}/records][%d] GetDomainsDomainRecords default  %+v", o._statusCode, o.Payload)
}

func (o *GetDomainsDomainRecordsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
