// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetDomainsDomainRecordsNameTypeParams creates a new GetDomainsDomainRecordsNameTypeParams object
// with the default values initialized.
func NewGetDomainsDomainRecordsNameTypeParams() *GetDomainsDomainRecordsNameTypeParams {
	var ()
	return &GetDomainsDomainRecordsNameTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsDomainRecordsNameTypeParamsWithTimeout creates a new GetDomainsDomainRecordsNameTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainsDomainRecordsNameTypeParamsWithTimeout(timeout time.Duration) *GetDomainsDomainRecordsNameTypeParams {
	var ()
	return &GetDomainsDomainRecordsNameTypeParams{

		timeout: timeout,
	}
}

// NewGetDomainsDomainRecordsNameTypeParamsWithContext creates a new GetDomainsDomainRecordsNameTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainsDomainRecordsNameTypeParamsWithContext(ctx context.Context) *GetDomainsDomainRecordsNameTypeParams {
	var ()
	return &GetDomainsDomainRecordsNameTypeParams{

		Context: ctx,
	}
}

// NewGetDomainsDomainRecordsNameTypeParamsWithHTTPClient creates a new GetDomainsDomainRecordsNameTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDomainsDomainRecordsNameTypeParamsWithHTTPClient(client *http.Client) *GetDomainsDomainRecordsNameTypeParams {
	var ()
	return &GetDomainsDomainRecordsNameTypeParams{
		HTTPClient: client,
	}
}

/*GetDomainsDomainRecordsNameTypeParams contains all the parameters to send to the API endpoint
for the get domains domain records name type operation typically these are written to a http.Request
*/
type GetDomainsDomainRecordsNameTypeParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*Name
	  record name to inspect

	*/
	Name string
	/*Type
	  record type to inspect

	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithTimeout(timeout time.Duration) *GetDomainsDomainRecordsNameTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithContext(ctx context.Context) *GetDomainsDomainRecordsNameTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithHTTPClient(client *http.Client) *GetDomainsDomainRecordsNameTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithDomain(domain string) *GetDomainsDomainRecordsNameTypeParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithName adds the name to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithName(name string) *GetDomainsDomainRecordsNameTypeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetName(name string) {
	o.Name = name
}

// WithType adds the typeVar to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) WithType(typeVar string) *GetDomainsDomainRecordsNameTypeParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get domains domain records name type params
func (o *GetDomainsDomainRecordsNameTypeParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsDomainRecordsNameTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
