// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetDomainsDomainRecordsRecordNameReader is a Reader for the GetDomainsDomainRecordsRecordName structure.
type GetDomainsDomainRecordsRecordNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsDomainRecordsRecordNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDomainsDomainRecordsRecordNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDomainsDomainRecordsRecordNameOK creates a GetDomainsDomainRecordsRecordNameOK with default headers values
func NewGetDomainsDomainRecordsRecordNameOK() *GetDomainsDomainRecordsRecordNameOK {
	return &GetDomainsDomainRecordsRecordNameOK{}
}

/*GetDomainsDomainRecordsRecordNameOK handles this case with default header values.

OK
*/
type GetDomainsDomainRecordsRecordNameOK struct {
	Payload []*models.Record
}

func (o *GetDomainsDomainRecordsRecordNameOK) Error() string {
	return fmt.Sprintf("[GET /domains/{domain}/records/{record_name}][%d] getDomainsDomainRecordsRecordNameOK  %+v", 200, o.Payload)
}

func (o *GetDomainsDomainRecordsRecordNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
