// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
	"golang.org/x/net/context"
)

// NewPostDomainsDomainRecordsParams creates a new PostDomainsDomainRecordsParams object
// with the default values initialized.
func NewPostDomainsDomainRecordsParams() *PostDomainsDomainRecordsParams {
	var ()
	return &PostDomainsDomainRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDomainsDomainRecordsParamsWithTimeout creates a new PostDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDomainsDomainRecordsParamsWithTimeout(timeout time.Duration) *PostDomainsDomainRecordsParams {
	var ()
	return &PostDomainsDomainRecordsParams{

		timeout: timeout,
	}
}

// NewPostDomainsDomainRecordsParamsWithContext creates a new PostDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDomainsDomainRecordsParamsWithContext(ctx context.Context) *PostDomainsDomainRecordsParams {
	var ()
	return &PostDomainsDomainRecordsParams{

		Context: ctx,
	}
}

// NewPostDomainsDomainRecordsParamsWithHTTPClient creates a new PostDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDomainsDomainRecordsParamsWithHTTPClient(client *http.Client) *PostDomainsDomainRecordsParams {
	var ()
	return &PostDomainsDomainRecordsParams{
		HTTPClient: client,
	}
}

/*PostDomainsDomainRecordsParams contains all the parameters to send to the API endpoint
for the post domains domain records operation typically these are written to a http.Request
*/
type PostDomainsDomainRecordsParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*Record
	  Record to add

	*/
	Record *models.Record

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) WithTimeout(timeout time.Duration) *PostDomainsDomainRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) WithContext(ctx context.Context) *PostDomainsDomainRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) WithHTTPClient(client *http.Client) *PostDomainsDomainRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) WithDomain(domain string) *PostDomainsDomainRecordsParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithRecord adds the record to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) WithRecord(record *models.Record) *PostDomainsDomainRecordsParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the post domains domain records params
func (o *PostDomainsDomainRecordsParams) SetRecord(record *models.Record) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PostDomainsDomainRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
