// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PutDomainsDomainRecordsRecordNameRecordTypeReader is a Reader for the PutDomainsDomainRecordsRecordNameRecordType structure.
type PutDomainsDomainRecordsRecordNameRecordTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDomainsDomainRecordsRecordNameRecordTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutDomainsDomainRecordsRecordNameRecordTypeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutDomainsDomainRecordsRecordNameRecordTypeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutDomainsDomainRecordsRecordNameRecordTypeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeCreated creates a PutDomainsDomainRecordsRecordNameRecordTypeCreated with default headers values
func NewPutDomainsDomainRecordsRecordNameRecordTypeCreated() *PutDomainsDomainRecordsRecordNameRecordTypeCreated {
	return &PutDomainsDomainRecordsRecordNameRecordTypeCreated{}
}

/*PutDomainsDomainRecordsRecordNameRecordTypeCreated handles this case with default header values.

OK
*/
type PutDomainsDomainRecordsRecordNameRecordTypeCreated struct {
	Payload *models.Return200
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeCreated) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records/{record_name}/{record_type}][%d] putDomainsDomainRecordsRecordNameRecordTypeCreated  %+v", 201, o.Payload)
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeBadRequest creates a PutDomainsDomainRecordsRecordNameRecordTypeBadRequest with default headers values
func NewPutDomainsDomainRecordsRecordNameRecordTypeBadRequest() *PutDomainsDomainRecordsRecordNameRecordTypeBadRequest {
	return &PutDomainsDomainRecordsRecordNameRecordTypeBadRequest{}
}

/*PutDomainsDomainRecordsRecordNameRecordTypeBadRequest handles this case with default header values.

Not OK
*/
type PutDomainsDomainRecordsRecordNameRecordTypeBadRequest struct {
	Payload *models.Return400
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeBadRequest) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records/{record_name}/{record_type}][%d] putDomainsDomainRecordsRecordNameRecordTypeBadRequest  %+v", 400, o.Payload)
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeDefault creates a PutDomainsDomainRecordsRecordNameRecordTypeDefault with default headers values
func NewPutDomainsDomainRecordsRecordNameRecordTypeDefault(code int) *PutDomainsDomainRecordsRecordNameRecordTypeDefault {
	return &PutDomainsDomainRecordsRecordNameRecordTypeDefault{
		_statusCode: code,
	}
}

/*PutDomainsDomainRecordsRecordNameRecordTypeDefault handles this case with default header values.

Unexpected error
*/
type PutDomainsDomainRecordsRecordNameRecordTypeDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the put domains domain records record name record type default response
func (o *PutDomainsDomainRecordsRecordNameRecordTypeDefault) Code() int {
	return o._statusCode
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeDefault) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records/{record_name}/{record_type}][%d] PutDomainsDomainRecordsRecordNameRecordType default  %+v", o._statusCode, o.Payload)
}

func (o *PutDomainsDomainRecordsRecordNameRecordTypeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
