// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
	"golang.org/x/net/context"
)

// NewPutDomainsDomainRecordsRecordNameRecordTypeParams creates a new PutDomainsDomainRecordsRecordNameRecordTypeParams object
// with the default values initialized.
func NewPutDomainsDomainRecordsRecordNameRecordTypeParams() *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	var ()
	return &PutDomainsDomainRecordsRecordNameRecordTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithTimeout creates a new PutDomainsDomainRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithTimeout(timeout time.Duration) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	var ()
	return &PutDomainsDomainRecordsRecordNameRecordTypeParams{

		timeout: timeout,
	}
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithContext creates a new PutDomainsDomainRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithContext(ctx context.Context) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	var ()
	return &PutDomainsDomainRecordsRecordNameRecordTypeParams{

		Context: ctx,
	}
}

// NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithHTTPClient creates a new PutDomainsDomainRecordsRecordNameRecordTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDomainsDomainRecordsRecordNameRecordTypeParamsWithHTTPClient(client *http.Client) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	var ()
	return &PutDomainsDomainRecordsRecordNameRecordTypeParams{
		HTTPClient: client,
	}
}

/*PutDomainsDomainRecordsRecordNameRecordTypeParams contains all the parameters to send to the API endpoint
for the put domains domain records record name record type operation typically these are written to a http.Request
*/
type PutDomainsDomainRecordsRecordNameRecordTypeParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*Record
	  Record to add

	*/
	Record *models.Record
	/*RecordName
	  Domain to inspect

	*/
	RecordName string
	/*RecordType
	  record type to inspect

	*/
	RecordType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithTimeout(timeout time.Duration) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithContext(ctx context.Context) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithHTTPClient(client *http.Client) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithDomain(domain string) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithRecord adds the record to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithRecord(record *models.Record) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetRecord(record *models.Record) {
	o.Record = record
}

// WithRecordName adds the recordName to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithRecordName(recordName string) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetRecordName(recordName)
	return o
}

// SetRecordName adds the recordName to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetRecordName(recordName string) {
	o.RecordName = recordName
}

// WithRecordType adds the recordType to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WithRecordType(recordType string) *PutDomainsDomainRecordsRecordNameRecordTypeParams {
	o.SetRecordType(recordType)
	return o
}

// SetRecordType adds the recordType to the put domains domain records record name record type params
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) SetRecordType(recordType string) {
	o.RecordType = recordType
}

// WriteToRequest writes these params to a swagger request
func (o *PutDomainsDomainRecordsRecordNameRecordTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	// path param record_name
	if err := r.SetPathParam("record_name", o.RecordName); err != nil {
		return err
	}

	// path param record_type
	if err := r.SetPathParam("record_type", o.RecordType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
