// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PutDomainsDomainRecordsReader is a Reader for the PutDomainsDomainRecords structure.
type PutDomainsDomainRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDomainsDomainRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPutDomainsDomainRecordsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutDomainsDomainRecordsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutDomainsDomainRecordsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutDomainsDomainRecordsCreated creates a PutDomainsDomainRecordsCreated with default headers values
func NewPutDomainsDomainRecordsCreated() *PutDomainsDomainRecordsCreated {
	return &PutDomainsDomainRecordsCreated{}
}

/*PutDomainsDomainRecordsCreated handles this case with default header values.

OK
*/
type PutDomainsDomainRecordsCreated struct {
	Payload *models.Return200
}

func (o *PutDomainsDomainRecordsCreated) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records][%d] putDomainsDomainRecordsCreated  %+v", 201, o.Payload)
}

func (o *PutDomainsDomainRecordsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsDomainRecordsBadRequest creates a PutDomainsDomainRecordsBadRequest with default headers values
func NewPutDomainsDomainRecordsBadRequest() *PutDomainsDomainRecordsBadRequest {
	return &PutDomainsDomainRecordsBadRequest{}
}

/*PutDomainsDomainRecordsBadRequest handles this case with default header values.

Not OK
*/
type PutDomainsDomainRecordsBadRequest struct {
	Payload *models.Return400
}

func (o *PutDomainsDomainRecordsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records][%d] putDomainsDomainRecordsBadRequest  %+v", 400, o.Payload)
}

func (o *PutDomainsDomainRecordsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsDomainRecordsDefault creates a PutDomainsDomainRecordsDefault with default headers values
func NewPutDomainsDomainRecordsDefault(code int) *PutDomainsDomainRecordsDefault {
	return &PutDomainsDomainRecordsDefault{
		_statusCode: code,
	}
}

/*PutDomainsDomainRecordsDefault handles this case with default header values.

Unexpected error
*/
type PutDomainsDomainRecordsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the put domains domain records default response
func (o *PutDomainsDomainRecordsDefault) Code() int {
	return o._statusCode
}

func (o *PutDomainsDomainRecordsDefault) Error() string {
	return fmt.Sprintf("[PUT /domains/{domain}/records][%d] PutDomainsDomainRecords default  %+v", o._statusCode, o.Payload)
}

func (o *PutDomainsDomainRecordsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PutDomainsDomainRecordsBody put domains domain records body
swagger:model PutDomainsDomainRecordsBody
*/
type PutDomainsDomainRecordsBody struct {

	// items
	Items []*models.Record `json:"items"`
}

// Validate validates this put domains domain records body
func (o *PutDomainsDomainRecordsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutDomainsDomainRecordsBody) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("record" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutDomainsDomainRecordsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutDomainsDomainRecordsBody) UnmarshalBinary(b []byte) error {
	var res PutDomainsDomainRecordsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
