// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPutDomainsDomainRecordsParams creates a new PutDomainsDomainRecordsParams object
// with the default values initialized.
func NewPutDomainsDomainRecordsParams() *PutDomainsDomainRecordsParams {
	var ()
	return &PutDomainsDomainRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDomainsDomainRecordsParamsWithTimeout creates a new PutDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDomainsDomainRecordsParamsWithTimeout(timeout time.Duration) *PutDomainsDomainRecordsParams {
	var ()
	return &PutDomainsDomainRecordsParams{

		timeout: timeout,
	}
}

// NewPutDomainsDomainRecordsParamsWithContext creates a new PutDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDomainsDomainRecordsParamsWithContext(ctx context.Context) *PutDomainsDomainRecordsParams {
	var ()
	return &PutDomainsDomainRecordsParams{

		Context: ctx,
	}
}

// NewPutDomainsDomainRecordsParamsWithHTTPClient creates a new PutDomainsDomainRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDomainsDomainRecordsParamsWithHTTPClient(client *http.Client) *PutDomainsDomainRecordsParams {
	var ()
	return &PutDomainsDomainRecordsParams{
		HTTPClient: client,
	}
}

/*PutDomainsDomainRecordsParams contains all the parameters to send to the API endpoint
for the put domains domain records operation typically these are written to a http.Request
*/
type PutDomainsDomainRecordsParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*Record
	  Record to add

	*/
	Record PutDomainsDomainRecordsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) WithTimeout(timeout time.Duration) *PutDomainsDomainRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) WithContext(ctx context.Context) *PutDomainsDomainRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) WithHTTPClient(client *http.Client) *PutDomainsDomainRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) WithDomain(domain string) *PutDomainsDomainRecordsParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithRecord adds the record to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) WithRecord(record PutDomainsDomainRecordsBody) *PutDomainsDomainRecordsParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the put domains domain records params
func (o *PutDomainsDomainRecordsParams) SetRecord(record PutDomainsDomainRecordsBody) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PutDomainsDomainRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Record); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
