// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetZonesUUIDSnapshotsReader is a Reader for the GetZonesUUIDSnapshots structure.
type GetZonesUUIDSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetZonesUUIDSnapshotsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetZonesUUIDSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetZonesUUIDSnapshotsOK creates a GetZonesUUIDSnapshotsOK with default headers values
func NewGetZonesUUIDSnapshotsOK() *GetZonesUUIDSnapshotsOK {
	return &GetZonesUUIDSnapshotsOK{}
}

/*GetZonesUUIDSnapshotsOK handles this case with default header values.

OK
*/
type GetZonesUUIDSnapshotsOK struct {
	Payload []*GetZonesUUIDSnapshotsOKBodyItems0
}

func (o *GetZonesUUIDSnapshotsOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/snapshots][%d] getZonesUuidSnapshotsOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesUUIDSnapshotsBadRequest creates a GetZonesUUIDSnapshotsBadRequest with default headers values
func NewGetZonesUUIDSnapshotsBadRequest() *GetZonesUUIDSnapshotsBadRequest {
	return &GetZonesUUIDSnapshotsBadRequest{}
}

/*GetZonesUUIDSnapshotsBadRequest handles this case with default header values.

Not OK
*/
type GetZonesUUIDSnapshotsBadRequest struct {
	Payload *models.Return400
}

func (o *GetZonesUUIDSnapshotsBadRequest) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/snapshots][%d] getZonesUuidSnapshotsBadRequest  %+v", 400, o.Payload)
}

func (o *GetZonesUUIDSnapshotsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesUUIDSnapshotsDefault creates a GetZonesUUIDSnapshotsDefault with default headers values
func NewGetZonesUUIDSnapshotsDefault(code int) *GetZonesUUIDSnapshotsDefault {
	return &GetZonesUUIDSnapshotsDefault{
		_statusCode: code,
	}
}

/*GetZonesUUIDSnapshotsDefault handles this case with default header values.

Unexpected error
*/
type GetZonesUUIDSnapshotsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the get zones UUID snapshots default response
func (o *GetZonesUUIDSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *GetZonesUUIDSnapshotsDefault) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/snapshots][%d] GetZonesUUIDSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *GetZonesUUIDSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetZonesUUIDSnapshotsOKBodyItems0 get zones UUID snapshots o k body items0
swagger:model GetZonesUUIDSnapshotsOKBodyItems0
*/
type GetZonesUUIDSnapshotsOKBodyItems0 struct {

	// date created
	DateCreated string `json:"date_created,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this get zones UUID snapshots o k body items0
func (o *GetZonesUUIDSnapshotsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetZonesUUIDSnapshotsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetZonesUUIDSnapshotsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetZonesUUIDSnapshotsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
