// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDSnapshotsParams creates a new GetZonesUUIDSnapshotsParams object
// with the default values initialized.
func NewGetZonesUUIDSnapshotsParams() *GetZonesUUIDSnapshotsParams {
	var ()
	return &GetZonesUUIDSnapshotsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDSnapshotsParamsWithTimeout creates a new GetZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDSnapshotsParamsWithTimeout(timeout time.Duration) *GetZonesUUIDSnapshotsParams {
	var ()
	return &GetZonesUUIDSnapshotsParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDSnapshotsParamsWithContext creates a new GetZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDSnapshotsParamsWithContext(ctx context.Context) *GetZonesUUIDSnapshotsParams {
	var ()
	return &GetZonesUUIDSnapshotsParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDSnapshotsParamsWithHTTPClient creates a new GetZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDSnapshotsParamsWithHTTPClient(client *http.Client) *GetZonesUUIDSnapshotsParams {
	var ()
	return &GetZonesUUIDSnapshotsParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDSnapshotsParams contains all the parameters to send to the API endpoint
for the get zones UUID snapshots operation typically these are written to a http.Request
*/
type GetZonesUUIDSnapshotsParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) WithTimeout(timeout time.Duration) *GetZonesUUIDSnapshotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) WithContext(ctx context.Context) *GetZonesUUIDSnapshotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) WithHTTPClient(client *http.Client) *GetZonesUUIDSnapshotsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) WithUUID(uuid string) *GetZonesUUIDSnapshotsParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID snapshots params
func (o *GetZonesUUIDSnapshotsParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDSnapshotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
