// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDSnapshotsSnapshotUUIDParams creates a new GetZonesUUIDSnapshotsSnapshotUUIDParams object
// with the default values initialized.
func NewGetZonesUUIDSnapshotsSnapshotUUIDParams() *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	var ()
	return &GetZonesUUIDSnapshotsSnapshotUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithTimeout creates a new GetZonesUUIDSnapshotsSnapshotUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithTimeout(timeout time.Duration) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	var ()
	return &GetZonesUUIDSnapshotsSnapshotUUIDParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithContext creates a new GetZonesUUIDSnapshotsSnapshotUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithContext(ctx context.Context) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	var ()
	return &GetZonesUUIDSnapshotsSnapshotUUIDParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithHTTPClient creates a new GetZonesUUIDSnapshotsSnapshotUUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDSnapshotsSnapshotUUIDParamsWithHTTPClient(client *http.Client) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	var ()
	return &GetZonesUUIDSnapshotsSnapshotUUIDParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDSnapshotsSnapshotUUIDParams contains all the parameters to send to the API endpoint
for the get zones UUID snapshots snapshot UUID operation typically these are written to a http.Request
*/
type GetZonesUUIDSnapshotsSnapshotUUIDParams struct {

	/*SnapshotUUID
	  Snapshot uuid

	*/
	SnapshotUUID string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WithTimeout(timeout time.Duration) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WithContext(ctx context.Context) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WithHTTPClient(client *http.Client) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSnapshotUUID adds the snapshotUUID to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WithSnapshotUUID(snapshotUUID string) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	o.SetSnapshotUUID(snapshotUUID)
	return o
}

// SetSnapshotUUID adds the snapshotUuid to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) SetSnapshotUUID(snapshotUUID string) {
	o.SnapshotUUID = snapshotUUID
}

// WithUUID adds the uuid to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WithUUID(uuid string) *GetZonesUUIDSnapshotsSnapshotUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID snapshots snapshot UUID params
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDSnapshotsSnapshotUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param snapshot_uuid
	if err := r.SetPathParam("snapshot_uuid", o.SnapshotUUID); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
