// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostZonesUUIDSnapshotsParams creates a new PostZonesUUIDSnapshotsParams object
// with the default values initialized.
func NewPostZonesUUIDSnapshotsParams() *PostZonesUUIDSnapshotsParams {
	var ()
	return &PostZonesUUIDSnapshotsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostZonesUUIDSnapshotsParamsWithTimeout creates a new PostZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostZonesUUIDSnapshotsParamsWithTimeout(timeout time.Duration) *PostZonesUUIDSnapshotsParams {
	var ()
	return &PostZonesUUIDSnapshotsParams{

		timeout: timeout,
	}
}

// NewPostZonesUUIDSnapshotsParamsWithContext creates a new PostZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostZonesUUIDSnapshotsParamsWithContext(ctx context.Context) *PostZonesUUIDSnapshotsParams {
	var ()
	return &PostZonesUUIDSnapshotsParams{

		Context: ctx,
	}
}

// NewPostZonesUUIDSnapshotsParamsWithHTTPClient creates a new PostZonesUUIDSnapshotsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostZonesUUIDSnapshotsParamsWithHTTPClient(client *http.Client) *PostZonesUUIDSnapshotsParams {
	var ()
	return &PostZonesUUIDSnapshotsParams{
		HTTPClient: client,
	}
}

/*PostZonesUUIDSnapshotsParams contains all the parameters to send to the API endpoint
for the post zones UUID snapshots operation typically these are written to a http.Request
*/
type PostZonesUUIDSnapshotsParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) WithTimeout(timeout time.Duration) *PostZonesUUIDSnapshotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) WithContext(ctx context.Context) *PostZonesUUIDSnapshotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) WithHTTPClient(client *http.Client) *PostZonesUUIDSnapshotsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) WithUUID(uuid string) *PostZonesUUIDSnapshotsParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the post zones UUID snapshots params
func (o *PostZonesUUIDSnapshotsParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PostZonesUUIDSnapshotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
