// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new snapshots API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for snapshots API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetZonesUUIDSnapshots lists snapshots for a given zone

Optional extended description in Markdown.
*/
func (a *Client) GetZonesUUIDSnapshots(params *GetZonesUUIDSnapshotsParams, authInfo runtime.ClientAuthInfoWriter) (*GetZonesUUIDSnapshotsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetZonesUUIDSnapshotsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetZonesUUIDSnapshots",
		Method:             "GET",
		PathPattern:        "/zones/{uuid}/snapshots",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetZonesUUIDSnapshotsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetZonesUUIDSnapshotsOK), nil

}

/*
GetZonesUUIDSnapshotsSnapshotUUID creates a snapshot of a zone

Optional extended description in Markdown.
*/
func (a *Client) GetZonesUUIDSnapshotsSnapshotUUID(params *GetZonesUUIDSnapshotsSnapshotUUIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetZonesUUIDSnapshotsSnapshotUUIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetZonesUUIDSnapshotsSnapshotUUIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetZonesUUIDSnapshotsSnapshotUUID",
		Method:             "GET",
		PathPattern:        "/zones/{uuid}/snapshots/{snapshot_uuid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetZonesUUIDSnapshotsSnapshotUUIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetZonesUUIDSnapshotsSnapshotUUIDOK), nil

}

/*
PostZonesUUIDSnapshots creates a snapshot of a DNS zone

Optional extended description in Markdown.
*/
func (a *Client) PostZonesUUIDSnapshots(params *PostZonesUUIDSnapshotsParams, authInfo runtime.ClientAuthInfoWriter) (*PostZonesUUIDSnapshotsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostZonesUUIDSnapshotsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostZonesUUIDSnapshots",
		Method:             "POST",
		PathPattern:        "/zones/{uuid}/snapshots",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostZonesUUIDSnapshotsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostZonesUUIDSnapshotsCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
