// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteZonesUUIDParams creates a new DeleteZonesUUIDParams object
// with the default values initialized.
func NewDeleteZonesUUIDParams() *DeleteZonesUUIDParams {
	var ()
	return &DeleteZonesUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteZonesUUIDParamsWithTimeout creates a new DeleteZonesUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteZonesUUIDParamsWithTimeout(timeout time.Duration) *DeleteZonesUUIDParams {
	var ()
	return &DeleteZonesUUIDParams{

		timeout: timeout,
	}
}

// NewDeleteZonesUUIDParamsWithContext creates a new DeleteZonesUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteZonesUUIDParamsWithContext(ctx context.Context) *DeleteZonesUUIDParams {
	var ()
	return &DeleteZonesUUIDParams{

		Context: ctx,
	}
}

// NewDeleteZonesUUIDParamsWithHTTPClient creates a new DeleteZonesUUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteZonesUUIDParamsWithHTTPClient(client *http.Client) *DeleteZonesUUIDParams {
	var ()
	return &DeleteZonesUUIDParams{
		HTTPClient: client,
	}
}

/*DeleteZonesUUIDParams contains all the parameters to send to the API endpoint
for the delete zones UUID operation typically these are written to a http.Request
*/
type DeleteZonesUUIDParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete zones UUID params
func (o *DeleteZonesUUIDParams) WithTimeout(timeout time.Duration) *DeleteZonesUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete zones UUID params
func (o *DeleteZonesUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete zones UUID params
func (o *DeleteZonesUUIDParams) WithContext(ctx context.Context) *DeleteZonesUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete zones UUID params
func (o *DeleteZonesUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete zones UUID params
func (o *DeleteZonesUUIDParams) WithHTTPClient(client *http.Client) *DeleteZonesUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete zones UUID params
func (o *DeleteZonesUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the delete zones UUID params
func (o *DeleteZonesUUIDParams) WithUUID(uuid string) *DeleteZonesUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete zones UUID params
func (o *DeleteZonesUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteZonesUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
