// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/tokart/gandi-livedns-go/models"
)

// DeleteZonesUUIDReader is a Reader for the DeleteZonesUUID structure.
type DeleteZonesUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteZonesUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteZonesUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteZonesUUIDOK creates a DeleteZonesUUIDOK with default headers values
func NewDeleteZonesUUIDOK() *DeleteZonesUUIDOK {
	return &DeleteZonesUUIDOK{}
}

/*DeleteZonesUUIDOK handles this case with default header values.

OK
*/
type DeleteZonesUUIDOK struct {
	Payload *models.Zone
}

func (o *DeleteZonesUUIDOK) Error() string {
	return fmt.Sprintf("[DELETE /zones/{uuid}][%d] deleteZonesUuidOK  %+v", 200, o.Payload)
}

func (o *DeleteZonesUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
