// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetZonesUUIDDomainsReader is a Reader for the GetZonesUUIDDomains structure.
type GetZonesUUIDDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDDomainsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetZonesUUIDDomainsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetZonesUUIDDomainsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetZonesUUIDDomainsOK creates a GetZonesUUIDDomainsOK with default headers values
func NewGetZonesUUIDDomainsOK() *GetZonesUUIDDomainsOK {
	return &GetZonesUUIDDomainsOK{}
}

/*GetZonesUUIDDomainsOK handles this case with default header values.

OK
*/
type GetZonesUUIDDomainsOK struct {
	Payload []*GetZonesUUIDDomainsOKBodyItems0
}

func (o *GetZonesUUIDDomainsOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/domains][%d] getZonesUuidDomainsOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDDomainsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesUUIDDomainsBadRequest creates a GetZonesUUIDDomainsBadRequest with default headers values
func NewGetZonesUUIDDomainsBadRequest() *GetZonesUUIDDomainsBadRequest {
	return &GetZonesUUIDDomainsBadRequest{}
}

/*GetZonesUUIDDomainsBadRequest handles this case with default header values.

Not OK
*/
type GetZonesUUIDDomainsBadRequest struct {
	Payload *models.Return400
}

func (o *GetZonesUUIDDomainsBadRequest) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/domains][%d] getZonesUuidDomainsBadRequest  %+v", 400, o.Payload)
}

func (o *GetZonesUUIDDomainsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZonesUUIDDomainsDefault creates a GetZonesUUIDDomainsDefault with default headers values
func NewGetZonesUUIDDomainsDefault(code int) *GetZonesUUIDDomainsDefault {
	return &GetZonesUUIDDomainsDefault{
		_statusCode: code,
	}
}

/*GetZonesUUIDDomainsDefault handles this case with default header values.

Unexpected error
*/
type GetZonesUUIDDomainsDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the get zones UUID domains default response
func (o *GetZonesUUIDDomainsDefault) Code() int {
	return o._statusCode
}

func (o *GetZonesUUIDDomainsDefault) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}/domains][%d] GetZonesUUIDDomains default  %+v", o._statusCode, o.Payload)
}

func (o *GetZonesUUIDDomainsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetZonesUUIDDomainsOKBodyItems0 get zones UUID domains o k body items0
swagger:model GetZonesUUIDDomainsOKBodyItems0
*/
type GetZonesUUIDDomainsOKBodyItems0 struct {

	// fqdn
	Fqdn string `json:"fqdn,omitempty"`
}

// Validate validates this get zones UUID domains o k body items0
func (o *GetZonesUUIDDomainsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetZonesUUIDDomainsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetZonesUUIDDomainsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetZonesUUIDDomainsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
