// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// GetZonesUUIDReader is a Reader for the GetZonesUUID structure.
type GetZonesUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZonesUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZonesUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetZonesUUIDOK creates a GetZonesUUIDOK with default headers values
func NewGetZonesUUIDOK() *GetZonesUUIDOK {
	return &GetZonesUUIDOK{}
}

/*GetZonesUUIDOK handles this case with default header values.

OK
*/
type GetZonesUUIDOK struct {
	Payload *models.Zone
}

func (o *GetZonesUUIDOK) Error() string {
	return fmt.Sprintf("[GET /zones/{uuid}][%d] getZonesUuidOK  %+v", 200, o.Payload)
}

func (o *GetZonesUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
