// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetZonesUUIDDomainsParams creates a new GetZonesUUIDDomainsParams object
// with the default values initialized.
func NewGetZonesUUIDDomainsParams() *GetZonesUUIDDomainsParams {
	var ()
	return &GetZonesUUIDDomainsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZonesUUIDDomainsParamsWithTimeout creates a new GetZonesUUIDDomainsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZonesUUIDDomainsParamsWithTimeout(timeout time.Duration) *GetZonesUUIDDomainsParams {
	var ()
	return &GetZonesUUIDDomainsParams{

		timeout: timeout,
	}
}

// NewGetZonesUUIDDomainsParamsWithContext creates a new GetZonesUUIDDomainsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZonesUUIDDomainsParamsWithContext(ctx context.Context) *GetZonesUUIDDomainsParams {
	var ()
	return &GetZonesUUIDDomainsParams{

		Context: ctx,
	}
}

// NewGetZonesUUIDDomainsParamsWithHTTPClient creates a new GetZonesUUIDDomainsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZonesUUIDDomainsParamsWithHTTPClient(client *http.Client) *GetZonesUUIDDomainsParams {
	var ()
	return &GetZonesUUIDDomainsParams{
		HTTPClient: client,
	}
}

/*GetZonesUUIDDomainsParams contains all the parameters to send to the API endpoint
for the get zones UUID domains operation typically these are written to a http.Request
*/
type GetZonesUUIDDomainsParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) WithTimeout(timeout time.Duration) *GetZonesUUIDDomainsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) WithContext(ctx context.Context) *GetZonesUUIDDomainsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) WithHTTPClient(client *http.Client) *GetZonesUUIDDomainsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) WithUUID(uuid string) *GetZonesUUIDDomainsParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get zones UUID domains params
func (o *GetZonesUUIDDomainsParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetZonesUUIDDomainsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
