// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPatchZonesUUIDParams creates a new PatchZonesUUIDParams object
// with the default values initialized.
func NewPatchZonesUUIDParams() *PatchZonesUUIDParams {
	var ()
	return &PatchZonesUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchZonesUUIDParamsWithTimeout creates a new PatchZonesUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchZonesUUIDParamsWithTimeout(timeout time.Duration) *PatchZonesUUIDParams {
	var ()
	return &PatchZonesUUIDParams{

		timeout: timeout,
	}
}

// NewPatchZonesUUIDParamsWithContext creates a new PatchZonesUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchZonesUUIDParamsWithContext(ctx context.Context) *PatchZonesUUIDParams {
	var ()
	return &PatchZonesUUIDParams{

		Context: ctx,
	}
}

// NewPatchZonesUUIDParamsWithHTTPClient creates a new PatchZonesUUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchZonesUUIDParamsWithHTTPClient(client *http.Client) *PatchZonesUUIDParams {
	var ()
	return &PatchZonesUUIDParams{
		HTTPClient: client,
	}
}

/*PatchZonesUUIDParams contains all the parameters to send to the API endpoint
for the patch zones UUID operation typically these are written to a http.Request
*/
type PatchZonesUUIDParams struct {

	/*UUID
	  Zone uuid

	*/
	UUID string
	/*ZoneName
	  Zone name

	*/
	ZoneName PatchZonesUUIDBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch zones UUID params
func (o *PatchZonesUUIDParams) WithTimeout(timeout time.Duration) *PatchZonesUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch zones UUID params
func (o *PatchZonesUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch zones UUID params
func (o *PatchZonesUUIDParams) WithContext(ctx context.Context) *PatchZonesUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch zones UUID params
func (o *PatchZonesUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch zones UUID params
func (o *PatchZonesUUIDParams) WithHTTPClient(client *http.Client) *PatchZonesUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch zones UUID params
func (o *PatchZonesUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the patch zones UUID params
func (o *PatchZonesUUIDParams) WithUUID(uuid string) *PatchZonesUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the patch zones UUID params
func (o *PatchZonesUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WithZoneName adds the zoneName to the patch zones UUID params
func (o *PatchZonesUUIDParams) WithZoneName(zoneName PatchZonesUUIDBody) *PatchZonesUUIDParams {
	o.SetZoneName(zoneName)
	return o
}

// SetZoneName adds the zoneName to the patch zones UUID params
func (o *PatchZonesUUIDParams) SetZoneName(zoneName PatchZonesUUIDBody) {
	o.ZoneName = zoneName
}

// WriteToRequest writes these params to a swagger request
func (o *PatchZonesUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.ZoneName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
