// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostZonesUUIDDomainsDomainParams creates a new PostZonesUUIDDomainsDomainParams object
// with the default values initialized.
func NewPostZonesUUIDDomainsDomainParams() *PostZonesUUIDDomainsDomainParams {
	var ()
	return &PostZonesUUIDDomainsDomainParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostZonesUUIDDomainsDomainParamsWithTimeout creates a new PostZonesUUIDDomainsDomainParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostZonesUUIDDomainsDomainParamsWithTimeout(timeout time.Duration) *PostZonesUUIDDomainsDomainParams {
	var ()
	return &PostZonesUUIDDomainsDomainParams{

		timeout: timeout,
	}
}

// NewPostZonesUUIDDomainsDomainParamsWithContext creates a new PostZonesUUIDDomainsDomainParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostZonesUUIDDomainsDomainParamsWithContext(ctx context.Context) *PostZonesUUIDDomainsDomainParams {
	var ()
	return &PostZonesUUIDDomainsDomainParams{

		Context: ctx,
	}
}

// NewPostZonesUUIDDomainsDomainParamsWithHTTPClient creates a new PostZonesUUIDDomainsDomainParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostZonesUUIDDomainsDomainParamsWithHTTPClient(client *http.Client) *PostZonesUUIDDomainsDomainParams {
	var ()
	return &PostZonesUUIDDomainsDomainParams{
		HTTPClient: client,
	}
}

/*PostZonesUUIDDomainsDomainParams contains all the parameters to send to the API endpoint
for the post zones UUID domains domain operation typically these are written to a http.Request
*/
type PostZonesUUIDDomainsDomainParams struct {

	/*Domain
	  Domain to move

	*/
	Domain string
	/*UUID
	  Zone uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) WithTimeout(timeout time.Duration) *PostZonesUUIDDomainsDomainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) WithContext(ctx context.Context) *PostZonesUUIDDomainsDomainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) WithHTTPClient(client *http.Client) *PostZonesUUIDDomainsDomainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) WithDomain(domain string) *PostZonesUUIDDomainsDomainParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithUUID adds the uuid to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) WithUUID(uuid string) *PostZonesUUIDDomainsDomainParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the post zones UUID domains domain params
func (o *PostZonesUUIDDomainsDomainParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PostZonesUUIDDomainsDomainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
