// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PostZonesUUIDDomainsDomainReader is a Reader for the PostZonesUUIDDomainsDomain structure.
type PostZonesUUIDDomainsDomainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostZonesUUIDDomainsDomainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostZonesUUIDDomainsDomainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostZonesUUIDDomainsDomainBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostZonesUUIDDomainsDomainDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostZonesUUIDDomainsDomainOK creates a PostZonesUUIDDomainsDomainOK with default headers values
func NewPostZonesUUIDDomainsDomainOK() *PostZonesUUIDDomainsDomainOK {
	return &PostZonesUUIDDomainsDomainOK{}
}

/*PostZonesUUIDDomainsDomainOK handles this case with default header values.

OK
*/
type PostZonesUUIDDomainsDomainOK struct {
	Payload *models.Return200
}

func (o *PostZonesUUIDDomainsDomainOK) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/domains/{domain}][%d] postZonesUuidDomainsDomainOK  %+v", 200, o.Payload)
}

func (o *PostZonesUUIDDomainsDomainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesUUIDDomainsDomainBadRequest creates a PostZonesUUIDDomainsDomainBadRequest with default headers values
func NewPostZonesUUIDDomainsDomainBadRequest() *PostZonesUUIDDomainsDomainBadRequest {
	return &PostZonesUUIDDomainsDomainBadRequest{}
}

/*PostZonesUUIDDomainsDomainBadRequest handles this case with default header values.

Not OK
*/
type PostZonesUUIDDomainsDomainBadRequest struct {
	Payload *models.Return400
}

func (o *PostZonesUUIDDomainsDomainBadRequest) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/domains/{domain}][%d] postZonesUuidDomainsDomainBadRequest  %+v", 400, o.Payload)
}

func (o *PostZonesUUIDDomainsDomainBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesUUIDDomainsDomainDefault creates a PostZonesUUIDDomainsDomainDefault with default headers values
func NewPostZonesUUIDDomainsDomainDefault(code int) *PostZonesUUIDDomainsDomainDefault {
	return &PostZonesUUIDDomainsDomainDefault{
		_statusCode: code,
	}
}

/*PostZonesUUIDDomainsDomainDefault handles this case with default header values.

Unexpected error
*/
type PostZonesUUIDDomainsDomainDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the post zones UUID domains domain default response
func (o *PostZonesUUIDDomainsDomainDefault) Code() int {
	return o._statusCode
}

func (o *PostZonesUUIDDomainsDomainDefault) Error() string {
	return fmt.Sprintf("[POST /zones/{uuid}/domains/{domain}][%d] PostZonesUUIDDomainsDomain default  %+v", o._statusCode, o.Payload)
}

func (o *PostZonesUUIDDomainsDomainDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
