// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
	models "github.com/t0k4rt/gandi-livedns-go/models"
)

// PostZonesReader is a Reader for the PostZones structure.
type PostZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostZonesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostZonesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostZonesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostZonesCreated creates a PostZonesCreated with default headers values
func NewPostZonesCreated() *PostZonesCreated {
	return &PostZonesCreated{}
}

/*PostZonesCreated handles this case with default header values.

OK
*/
type PostZonesCreated struct {
	Payload *models.Return200
}

func (o *PostZonesCreated) Error() string {
	return fmt.Sprintf("[POST /zones][%d] postZonesCreated  %+v", 201, o.Payload)
}

func (o *PostZonesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesBadRequest creates a PostZonesBadRequest with default headers values
func NewPostZonesBadRequest() *PostZonesBadRequest {
	return &PostZonesBadRequest{}
}

/*PostZonesBadRequest handles this case with default header values.

Not OK
*/
type PostZonesBadRequest struct {
	Payload *models.Return400
}

func (o *PostZonesBadRequest) Error() string {
	return fmt.Sprintf("[POST /zones][%d] postZonesBadRequest  %+v", 400, o.Payload)
}

func (o *PostZonesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostZonesDefault creates a PostZonesDefault with default headers values
func NewPostZonesDefault(code int) *PostZonesDefault {
	return &PostZonesDefault{
		_statusCode: code,
	}
}

/*PostZonesDefault handles this case with default header values.

Unexpected error
*/
type PostZonesDefault struct {
	_statusCode int

	Payload *models.Return40x
}

// Code gets the status code for the post zones default response
func (o *PostZonesDefault) Code() int {
	return o._statusCode
}

func (o *PostZonesDefault) Error() string {
	return fmt.Sprintf("[POST /zones][%d] PostZones default  %+v", o._statusCode, o.Payload)
}

func (o *PostZonesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Return40x)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostZonesBody post zones body
swagger:model PostZonesBody
*/
type PostZonesBody struct {

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this post zones body
func (o *PostZonesBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostZonesBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("zoneName"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostZonesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostZonesBody) UnmarshalBinary(b []byte) error {
	var res PostZonesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
