// Code generated by go-swagger; DO NOT EDIT.

package dns_zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostZonesParams creates a new PostZonesParams object
// with the default values initialized.
func NewPostZonesParams() *PostZonesParams {
	var ()
	return &PostZonesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostZonesParamsWithTimeout creates a new PostZonesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostZonesParamsWithTimeout(timeout time.Duration) *PostZonesParams {
	var ()
	return &PostZonesParams{

		timeout: timeout,
	}
}

// NewPostZonesParamsWithContext creates a new PostZonesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostZonesParamsWithContext(ctx context.Context) *PostZonesParams {
	var ()
	return &PostZonesParams{

		Context: ctx,
	}
}

// NewPostZonesParamsWithHTTPClient creates a new PostZonesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostZonesParamsWithHTTPClient(client *http.Client) *PostZonesParams {
	var ()
	return &PostZonesParams{
		HTTPClient: client,
	}
}

/*PostZonesParams contains all the parameters to send to the API endpoint
for the post zones operation typically these are written to a http.Request
*/
type PostZonesParams struct {

	/*ZoneName
	  Zone name

	*/
	ZoneName PostZonesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post zones params
func (o *PostZonesParams) WithTimeout(timeout time.Duration) *PostZonesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post zones params
func (o *PostZonesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post zones params
func (o *PostZonesParams) WithContext(ctx context.Context) *PostZonesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post zones params
func (o *PostZonesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post zones params
func (o *PostZonesParams) WithHTTPClient(client *http.Client) *PostZonesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post zones params
func (o *PostZonesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithZoneName adds the zoneName to the post zones params
func (o *PostZonesParams) WithZoneName(zoneName PostZonesBody) *PostZonesParams {
	o.SetZoneName(zoneName)
	return o
}

// SetZoneName adds the zoneName to the post zones params
func (o *PostZonesParams) SetZoneName(zoneName PostZonesBody) {
	o.ZoneName = zoneName
}

// WriteToRequest writes these params to a swagger request
func (o *PostZonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ZoneName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
