// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetDomainsDomainRecordsNameParams creates a new GetDomainsDomainRecordsNameParams object
// with the default values initialized.
func NewGetDomainsDomainRecordsNameParams() *GetDomainsDomainRecordsNameParams {
	var ()
	return &GetDomainsDomainRecordsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsDomainRecordsNameParamsWithTimeout creates a new GetDomainsDomainRecordsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainsDomainRecordsNameParamsWithTimeout(timeout time.Duration) *GetDomainsDomainRecordsNameParams {
	var ()
	return &GetDomainsDomainRecordsNameParams{

		timeout: timeout,
	}
}

// NewGetDomainsDomainRecordsNameParamsWithContext creates a new GetDomainsDomainRecordsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainsDomainRecordsNameParamsWithContext(ctx context.Context) *GetDomainsDomainRecordsNameParams {
	var ()
	return &GetDomainsDomainRecordsNameParams{

		Context: ctx,
	}
}

// NewGetDomainsDomainRecordsNameParamsWithHTTPClient creates a new GetDomainsDomainRecordsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDomainsDomainRecordsNameParamsWithHTTPClient(client *http.Client) *GetDomainsDomainRecordsNameParams {
	var ()
	return &GetDomainsDomainRecordsNameParams{
		HTTPClient: client,
	}
}

/*GetDomainsDomainRecordsNameParams contains all the parameters to send to the API endpoint
for the get domains domain records name operation typically these are written to a http.Request
*/
type GetDomainsDomainRecordsNameParams struct {

	/*Domain
	  Domain to inspect

	*/
	Domain string
	/*Name
	  record name to inspect

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) WithTimeout(timeout time.Duration) *GetDomainsDomainRecordsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) WithContext(ctx context.Context) *GetDomainsDomainRecordsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) WithHTTPClient(client *http.Client) *GetDomainsDomainRecordsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) WithDomain(domain string) *GetDomainsDomainRecordsNameParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithName adds the name to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) WithName(name string) *GetDomainsDomainRecordsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get domains domain records name params
func (o *GetDomainsDomainRecordsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsDomainRecordsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
