// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "github.com/tokart/gandi-livedns-go/models"
)

// PostDomainsDomainRecordsReader is a Reader for the PostDomainsDomainRecords structure.
type PostDomainsDomainRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainsDomainRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostDomainsDomainRecordsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostDomainsDomainRecordsCreated creates a PostDomainsDomainRecordsCreated with default headers values
func NewPostDomainsDomainRecordsCreated() *PostDomainsDomainRecordsCreated {
	return &PostDomainsDomainRecordsCreated{}
}

/*PostDomainsDomainRecordsCreated handles this case with default header values.

OK
*/
type PostDomainsDomainRecordsCreated struct {
	Payload *models.ReturnMessage
}

func (o *PostDomainsDomainRecordsCreated) Error() string {
	return fmt.Sprintf("[POST /domains/{domain}/records][%d] postDomainsDomainRecordsCreated  %+v", 201, o.Payload)
}

func (o *PostDomainsDomainRecordsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
