// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Zone zone
// swagger:model Zone
type Zone struct {

	// email
	Email string `json:"email,omitempty"`

	// expire
	Expire int32 `json:"expire,omitempty"`

	// minimum
	Minimum int32 `json:"minimum,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// primary ns
	PrimaryNs string `json:"primary_ns,omitempty"`

	// refresh
	Refresh int32 `json:"refresh,omitempty"`

	// retry
	Retry int32 `json:"retry,omitempty"`

	// serial
	Serial int32 `json:"serial,omitempty"`

	// user uuid
	UserUUID string `json:"user_uuid,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this zone
func (m *Zone) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Zone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Zone) UnmarshalBinary(b []byte) error {
	var res Zone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
